### ISSUE TITLE
Crash when placing welcome mat

### ISSUE THREAD

**Issue by Craluminum2413** [91loocekaj/vs-merchant#2]
**Game Version:** 1.15.0-pre.3
**Mod Version:** 0.9.6
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.0-pre.3 (Unstable)06/18/2021 18:27:07: Critical error occurred
System.MissingFieldException: Field not found: 'Vintagestory.API.Common.CollectibleObject.Attributes'.
   at Merchant.BEWelcomeMat.get_minTravelDays()
   at Merchant.BEWelcomeMat.OnBlockPlaced(ItemStack byItemStack)
   at Vintagestory.Client.NoObf.ClientWorldMap.SpawnBlockEntity(String classname, BlockPos position, ItemStack byItemStack)
   at Vintagestory.API.Common.Block.OnBlockPlaced(IWorldAccessor world, BlockPos blockPos, ItemStack byItemStack)
   at Vintagestory.Common.BlockAccessorRelaxed.SetBlock(Int32 blockId, BlockPos pos, ItemStack byItemstack)
   at Vintagestory.API.Common.Block.DoPlaceBlock(IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel, ItemStack byItemStack)
   at Vintagestory.API.Common.Block.TryPlaceBlock(IWorldAccessor world, IPlayer byPlayer, ItemStack itemstack, BlockSelection blockSel, String& failureCode)
   at Vintagestory.Client.NoObf.ClientMain.OnPlayerTryPlace(BlockSelection blockSelection, String& failureCode)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnBlockBuild(BlockSelection blockSelection, Block onBlock, String& failureCode)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _kG3l18Uo58XQnaOroOTVL156lmd._LcGp6vp0iU0HbJoKtBq1oH3wJGn(Single )
   at _myXzIvBGuHgNhKsWypGDvkNbw4X._PeuIqQzFn7JdsiaCMO1A0nOHYOF(Single )
   at _myXzIvBGuHgNhKsWypGDvkNbw4X._12elMOUbssfuqzUtVoRc599RYNW(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _UwTpwIUKuzIrz4lc7aDEDr1w32f._ouD1c39oCQ2Eda0lkC3EXYeZtC7(_OdfjAwaG2wGU12XuYVt4myQv5bF , String[] )
   at _j9Ke4RlHC2L45ChATqqx7RI91CC._ouD1c39oCQ2Eda0lkC3EXYeZtC7(ThreadStart )
```

**Comment by Craluminum2413** [comment]
I will pretend this is fixed in 1.15
